server.port=8080
spring.application.name=ewm-service

# ???????? ??
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ewm-db:5432/ewm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:practicum}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:practicum}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.initialization-fail-timeout=10000
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL init
spring.sql.init.mode=always

# Stats Server
stats-server.url=${STATS_SERVER_URL:http://stats-server:9090}