name: Explore With Me API Tests

on:
 pull_request:  # Временно отключено до реализации всех эндпоинтов

jobs:
  build:
    uses: yandex-praktikum/java-explore-with-me-plus/.github/workflows/api-tests.yml@ci
